import {
  pgTable,
  uuid,
  varchar,
  integer,
  boolean,
  timestamp,
  text,
  real,
  index,
} from 'drizzle-orm/pg-core';

export const coupons = pgTable(
  'coupons',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    code: varchar('code', { length: 50 }).notNull().unique(),
    title: varchar('title', { length: 255 }).notNull(),
    description: text('description').notNull(),
    category: varchar('category', { length: 30 }).notNull(),
    platform: varchar('platform', { length: 30 }).notNull().default('all'),
    discountType: varchar('discount_type', { length: 20 }).notNull(),
    discountValue: integer('discount_value').notNull(),
    maxDiscountAmount: integer('max_discount_amount'),
    maxDiscountCurrency: varchar('max_discount_currency', { length: 3 }).default('INR'),
    minPurchaseAmount: integer('min_purchase_amount'),
    minPurchaseCurrency: varchar('min_purchase_currency', { length: 3 }).default('INR'),
    bankName: varchar('bank_name', { length: 100 }),
    cardNetwork: varchar('card_network', { length: 20 }),
    cardType: varchar('card_type', { length: 10 }),
    isStackable: boolean('is_stackable').notNull().default(false),
    stackableWith: varchar('stackable_with', { length: 50 }).array().notNull().default([]),
    usageLimit: integer('usage_limit'),
    usedCount: integer('used_count').notNull().default(0),
    perUserLimit: integer('per_user_limit'),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    isActive: boolean('is_active').notNull().default(true),
    isVerified: boolean('is_verified').notNull().default(false),
    successRate: real('success_rate'),
    lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }),
    termsAndConditions: text('terms_and_conditions').notNull().default(''),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    codeIdx: index('coupons_code_idx').on(t.code),
    categoryIdx: index('coupons_category_idx').on(t.category),
    platformIdx: index('coupons_platform_idx').on(t.platform),
    activeIdx: index('coupons_active_idx').on(t.isActive),
  }),
);

export const flashDeals = pgTable(
  'flash_deals',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    title: varchar('title', { length: 255 }).notNull(),
    subtitle: varchar('subtitle', { length: 255 }).notNull(),
    origin: varchar('origin', { length: 100 }).notNull(),
    destination: varchar('destination', { length: 100 }).notNull(),
    imageUrl: text('image_url').notNull(),
    salePriceAmount: integer('sale_price_amount').notNull(),
    salePriceCurrency: varchar('sale_price_currency', { length: 3 }).notNull().default('INR'),
    originalPriceAmount: integer('original_price_amount').notNull(),
    platform: varchar('platform', { length: 30 }).notNull(),
    deeplink: text('deeplink').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    seatsLeft: integer('seats_left'),
    isLive: boolean('is_live').notNull().default(true),
    dealType: varchar('deal_type', { length: 20 }).notNull().default('flash'),
    travelWindowFrom: varchar('travel_window_from', { length: 10 }).notNull(),
    travelWindowTo: varchar('travel_window_to', { length: 10 }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    liveIdx: index('fd_live_idx').on(t.isLive),
    expiresIdx: index('fd_expires_idx').on(t.expiresAt),
  }),
);
