import {
  pgTable,
  uuid,
  varchar,
  integer,
  real,
  timestamp,
  jsonb,
  index,
} from 'drizzle-orm/pg-core';

export const hotelSearchCache = pgTable(
  'hotel_search_cache',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    cacheKey: varchar('cache_key', { length: 512 }).notNull().unique(),
    destination: varchar('destination', { length: 255 }).notNull(),
    checkIn: varchar('check_in', { length: 10 }).notNull(),
    checkOut: varchar('check_out', { length: 10 }).notNull(),
    rooms: integer('rooms').notNull(),
    adults: integer('adults').notNull(),
    children: integer('children').notNull().default(0),
    resultsJson: jsonb('results_json').notNull(),
    resultCount: integer('result_count').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    cacheKeyIdx: index('hsc_cache_key_idx').on(t.cacheKey),
    destIdx: index('hsc_dest_idx').on(t.destination, t.checkIn, t.checkOut),
  }),
);

export const destinations = pgTable(
  'destinations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    name: varchar('name', { length: 150 }).notNull(),
    country: varchar('country', { length: 100 }).notNull(),
    countryCode: varchar('country_code', { length: 2 }).notNull(),
    continent: varchar('continent', { length: 30 }).notNull(),
    lat: varchar('lat', { length: 20 }).notNull(),
    lng: varchar('lng', { length: 20 }).notNull(),
    airportCodes: varchar('airport_codes', { length: 10 }).array().notNull().default([]),
    heroImageUrl: varchar('hero_image_url', { length: 1000 }).notNull(),
    imagesJson: jsonb('images_json').notNull().default([]),
    tagline: varchar('tagline', { length: 255 }).notNull(),
    description: varchar('description', { length: 2000 }).notNull(),
    moodsJson: jsonb('moods_json').notNull().default([]),
    scoreJson: jsonb('score_json').notNull(),
    budgetJson: jsonb('budget_json').notNull(),
    visaJson: jsonb('visa_json').notNull(),
    highlightsJson: jsonb('highlights_json').notNull().default([]),
    bestTimeJson: jsonb('best_time_json').notNull().default([]),
    popularActivities: varchar('popular_activities', { length: 200 }).array().notNull().default([]),
    cuisineHighlights: varchar('cuisine_highlights', { length: 100 }).array().notNull().default([]),
    localTips: varchar('local_tips', { length: 500 }).array().notNull().default([]),
    safetyRating: integer('safety_rating').notNull(),
    languageBarrier: varchar('language_barrier', { length: 10 }).notNull().default('low'),
    currency: varchar('currency', { length: 3 }).notNull(),
    timezoneName: varchar('timezone_name', { length: 50 }).notNull(),
    utcOffset: real('utc_offset').notNull(),
    isPopular: integer('is_popular').notNull().default(0),
    isTrending: integer('is_trending').notNull().default(0),
    isHiddenGem: integer('is_hidden_gem').notNull().default(0),
    rank: integer('rank').notNull().default(999),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    slugIdx: index('dest_slug_idx').on(t.slug),
    countryIdx: index('dest_country_idx').on(t.countryCode),
    continentIdx: index('dest_continent_idx').on(t.continent),
    rankIdx: index('dest_rank_idx').on(t.rank),
  }),
);
