import 'dotenv/config';
import { db } from '../config/database';
import { coupons, flashDeals } from './schema/deals';
import { destinations } from './schema/hotels';
import { logger } from '../shared/logger';

async function seed() {
  logger.info('Starting database seed...');

  // ─── Coupons ──────────────────────────────────────────────────────────────
  const couponData: (typeof coupons.$inferInsert)[] = [
    { code: 'FIRST500', title: 'First Booking ₹500 Off', description: 'Get ₹500 off on your first flight booking', category: 'flight', platform: 'makemytrip', discountType: 'flat', discountValue: 500, minPurchaseAmount: 2000, isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.92, termsAndConditions: 'Valid for new users only. Not valid with other offers.' },
    { code: 'MMT10OFF', title: '10% Off - MakeMyTrip', description: '10% off on flights, max ₹1500 discount', category: 'flight', platform: 'makemytrip', discountType: 'percent', discountValue: 10, maxDiscountAmount: 1500, minPurchaseAmount: 3000, isStackable: true, stackableWith: ['HDFC15'], isActive: true, isVerified: true, successRate: 0.87, termsAndConditions: 'Valid on all domestic and international flights.' },
    { code: 'HDFC15', title: 'HDFC Card 15% Off', description: '15% off for HDFC credit card holders', category: 'flight', platform: 'all', discountType: 'percent', discountValue: 15, maxDiscountAmount: 2000, minPurchaseAmount: 4000, bankName: 'HDFC Bank', cardNetwork: 'visa', cardType: 'credit', isStackable: true, stackableWith: ['MMT10OFF'], isActive: true, isVerified: true, successRate: 0.94, termsAndConditions: 'Valid on HDFC Visa and Mastercard credit cards only.' },
    { code: 'SBIFLY', title: 'SBI Card 12% Cashback', description: '12% cashback on flight bookings with SBI card', category: 'flight', platform: 'cleartrip', discountType: 'cashback', discountValue: 12, maxDiscountAmount: 1800, minPurchaseAmount: 5000, bankName: 'SBI', cardType: 'credit', isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.89, termsAndConditions: 'Cashback credited within 7 working days.' },
    { code: 'AXIS5', title: 'Axis Bank ₹5% Off', description: '5% instant discount on Axis credit cards', category: 'flight', platform: 'goibibo', discountType: 'percent', discountValue: 5, maxDiscountAmount: 800, minPurchaseAmount: 2000, bankName: 'Axis Bank', cardType: 'both', isStackable: true, stackableWith: [], isActive: true, isVerified: true, successRate: 0.91, termsAndConditions: 'Valid on Axis Bank Visa and Mastercard.' },
    { code: 'ICICI20', title: 'ICICI 20% Off Hotels', description: '20% off on hotel bookings with ICICI card', category: 'hotel', platform: 'makemytrip', discountType: 'percent', discountValue: 20, maxDiscountAmount: 3000, minPurchaseAmount: 5000, bankName: 'ICICI Bank', cardType: 'credit', isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.86, termsAndConditions: 'Valid on ICICI Bank credit cards for hotel bookings.' },
    { code: 'EASEMYTRIP8', title: 'EaseMyTrip 8% Off', description: '8% off on domestic flights with no upper limit', category: 'flight', platform: 'easemytrip', discountType: 'percent', discountValue: 8, minPurchaseAmount: 1500, isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.85, termsAndConditions: 'Valid on domestic one-way and round trip bookings.' },
    { code: 'PAYTM200', title: 'Paytm ₹200 Cashback', description: '₹200 Paytm cashback on flight bookings', category: 'flight', platform: 'paytm_travel', discountType: 'cashback', discountValue: 200, minPurchaseAmount: 2500, isStackable: true, stackableWith: [], isActive: true, isVerified: true, successRate: 0.88, termsAndConditions: 'Cashback added to Paytm wallet within 24 hours.' },
    { code: 'KOTAK25', title: 'Kotak 25% Off Flights', description: '25% discount on flight bookings with Kotak card', category: 'flight', platform: 'ixigo', discountType: 'percent', discountValue: 25, maxDiscountAmount: 2500, minPurchaseAmount: 6000, bankName: 'Kotak Bank', cardType: 'credit', isStackable: false, stackableWith: [], isActive: true, isVerified: false, successRate: 0.78, termsAndConditions: 'Valid on select Kotak credit cards. Check offer page.' },
    { code: 'YATRA15HOTEL', title: 'Yatra 15% Hotel Off', description: '15% off on hotel bookings via Yatra', category: 'hotel', platform: 'yatra', discountType: 'percent', discountValue: 15, maxDiscountAmount: 2000, minPurchaseAmount: 3000, isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.83, termsAndConditions: 'Valid on all domestic hotels.' },
    { code: 'NEWUSER1000', title: 'New User ₹1000 Off', description: 'Special discount for first-time Travel Sarthi users', category: 'flight', platform: 'makemytrip', discountType: 'flat', discountValue: 1000, minPurchaseAmount: 3000, perUserLimit: 1, isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.95, termsAndConditions: 'Valid once per user. Cannot be combined with other offers.' },
    { code: 'WEEKEND500', title: 'Weekend Getaway ₹500 Off', description: '₹500 off on weekend bookings (Fri-Sun)', category: 'hotel', platform: 'goibibo', discountType: 'flat', discountValue: 500, minPurchaseAmount: 2000, isStackable: true, stackableWith: [], isActive: true, isVerified: true, successRate: 0.90, termsAndConditions: 'Valid for check-in on Friday, Saturday, or Sunday.' },
    { code: 'BUSICLASS20', title: 'Business Class 20% Off', description: '20% off on business class bookings', category: 'flight', platform: 'all', discountType: 'percent', discountValue: 20, maxDiscountAmount: 10000, minPurchaseAmount: 20000, isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.82, termsAndConditions: 'Valid on business class flights only.' },
    { code: 'DUBAIFEST', title: 'Dubai Sale - ₹2000 Off', description: 'Special Dubai festival sale — ₹2000 instant off', category: 'flight', platform: 'all', discountType: 'flat', discountValue: 2000, minPurchaseAmount: 15000, expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.93, termsAndConditions: 'Valid on Dubai flights only. Limited time offer.' },
    { code: 'MONSOON15', title: 'Monsoon Special 15%', description: '15% off on domestic flights during monsoon season', category: 'flight', platform: 'cleartrip', discountType: 'percent', discountValue: 15, maxDiscountAmount: 1200, minPurchaseAmount: 3000, expiresAt: new Date('2026-09-30T23:59:59Z'), isStackable: true, stackableWith: [], isActive: true, isVerified: true, successRate: 0.87, termsAndConditions: 'Valid Jun-Sep 2026 on domestic flights.' },
    { code: 'GOA500', title: 'Goa Beach Pack ₹500 Off', description: '₹500 off on Goa hotel bookings', category: 'hotel', platform: 'makemytrip', discountType: 'flat', discountValue: 500, minPurchaseAmount: 2500, isStackable: true, stackableWith: [], isActive: true, isVerified: true, successRate: 0.91, termsAndConditions: 'Valid on Goa hotel bookings.' },
    { code: 'EARLYBRD', title: 'Early Bird 10% Off', description: '10% off when booking 60+ days in advance', category: 'flight', platform: 'all', discountType: 'percent', discountValue: 10, maxDiscountAmount: 2000, minPurchaseAmount: 5000, isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.89, termsAndConditions: 'Booking must be made at least 60 days before travel date.' },
    { code: 'GROUPFLY', title: 'Group Booking 12% Off', description: '12% off for group bookings of 5+ passengers', category: 'flight', platform: 'all', discountType: 'percent', discountValue: 12, maxDiscountAmount: 5000, minPurchaseAmount: 10000, isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.84, termsAndConditions: 'Valid for 5 or more passengers on the same booking.' },
    { code: 'INTL1500', title: 'International 15% Off', description: '15% off on international flight bookings', category: 'flight', platform: 'goibibo', discountType: 'percent', discountValue: 15, maxDiscountAmount: 3500, minPurchaseAmount: 15000, isStackable: false, stackableWith: [], isActive: true, isVerified: true, successRate: 0.86, termsAndConditions: 'Valid on all international flight bookings via Goibibo.' },
    { code: 'RUPAY10', title: 'RuPay Card 10% Off', description: '10% off with any RuPay card', category: 'flight', platform: 'all', discountType: 'percent', discountValue: 10, maxDiscountAmount: 1500, minPurchaseAmount: 3000, cardNetwork: 'rupay', cardType: 'both', isStackable: true, stackableWith: [], isActive: true, isVerified: true, successRate: 0.90, termsAndConditions: 'Valid on all RuPay debit and credit cards.' },
  ];

  await db.insert(coupons).values(couponData).onConflictDoNothing();
  logger.info(`Seeded ${couponData.length} coupons`);

  // ─── Destinations (120+) ──────────────────────────────────────────────────
  const destinationData: (typeof destinations.$inferInsert)[] = [
    // Asia
    { slug: 'dubai-uae', name: 'Dubai', country: 'United Arab Emirates', countryCode: 'AE', continent: 'middle_east', lat: '25.2048', lng: '55.2708', airportCodes: ['DXB', 'DWC'], heroImageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80', tagline: 'Where the Desert Meets the Future', description: 'Dubai is a city of superlatives — the tallest building, the largest mall, and the most extravagant hotels. Experience gold souks, desert safaris, and world-class dining.', moodsJson: ['shopping', 'luxury', 'food', 'culture'], scoreJson: { overall: 92, affordability: 45, safety: 95, weatherScore: 70, touristInfrastructure: 99, uniqueness: 85, visaEase: 90, travelTime: 80, communityRating: 89, badge: 'luxury' }, budgetJson: { budget: { amount: 8000, currency: 'INR', formatted: '₹8,000' }, comfort: { amount: 15000, currency: 'INR', formatted: '₹15,000' }, luxury: { amount: 35000, currency: 'INR', formatted: '₹35,000' }, flightFrom: { amount: 18000, currency: 'INR', formatted: '₹18,000' }, averageHotelPerNight: { amount: 8000, currency: 'INR', formatted: '₹8,000' }, averageMealCost: { amount: 1200, currency: 'INR', formatted: '₹1,200' } }, visaJson: { type: 'visa_on_arrival', durationDays: 30, feeUsd: 35, processingDays: 0, notes: 'Indian passport holders get visa on arrival' }, highlightsJson: [], bestTimeJson: [{ months: [10, 11, 12, 1, 2, 3], reason: 'Pleasant weather with temperatures 20-30°C', weather: 'Sunny and mild', crowdLevel: 'high', priceLevel: 'peak' }], popularActivities: ['Burj Khalifa', 'Desert Safari', 'Dubai Mall', 'Palm Jumeirah', 'Dubai Frame', 'Gold Souk', 'Dubai Creek', 'Miracle Garden'], cuisineHighlights: ['Shawarma', 'Mandi', 'Luqaimat', 'Harees', 'Machboos'], localTips: ['Visit in winter for best weather', 'Download RTA app for metro', 'Dress modestly in malls', 'Bargain in souks'], safetyRating: 10, languageBarrier: 'low', currency: 'AED', timezoneName: 'Asia/Dubai', utcOffset: 4, isPopular: 1, isTrending: 1, isHiddenGem: 0, rank: 1 },
    { slug: 'bangkok-thailand', name: 'Bangkok', country: 'Thailand', countryCode: 'TH', continent: 'asia', lat: '13.7563', lng: '100.5018', airportCodes: ['BKK', 'DMK'], heroImageUrl: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80', tagline: 'City of Angels — Street Food Capital of the World', description: 'Bangkok dazzles with ornate temples, floating markets, vibrant street food scenes, and world-class rooftop bars. An affordable city with infinite things to do.', moodsJson: ['food', 'culture', 'budget', 'nightlife'], scoreJson: { overall: 91, affordability: 85, safety: 75, weatherScore: 65, touristInfrastructure: 92, uniqueness: 88, visaEase: 85, travelTime: 88, communityRating: 92, badge: 'best_value' }, budgetJson: { budget: { amount: 3000, currency: 'INR', formatted: '₹3,000' }, comfort: { amount: 6000, currency: 'INR', formatted: '₹6,000' }, luxury: { amount: 15000, currency: 'INR', formatted: '₹15,000' }, flightFrom: { amount: 9000, currency: 'INR', formatted: '₹9,000' }, averageHotelPerNight: { amount: 3000, currency: 'INR', formatted: '₹3,000' }, averageMealCost: { amount: 400, currency: 'INR', formatted: '₹400' } }, visaJson: { type: 'visa_free', durationDays: 30, feeUsd: 0, notes: 'Indian passport — visa-free for 30 days' }, highlightsJson: [], bestTimeJson: [{ months: [11, 12, 1, 2, 3], reason: 'Cool and dry season', weather: 'Sunny, 25-32°C', crowdLevel: 'high', priceLevel: 'peak' }], popularActivities: ['Grand Palace', 'Chatuchak Market', 'Wat Pho', 'Khao San Road', 'Floating Markets', 'Muay Thai', 'Rooftop Bars', 'Tuk-Tuk Tour'], cuisineHighlights: ['Pad Thai', 'Tom Yum', 'Green Curry', 'Mango Sticky Rice', 'Som Tam'], localTips: ['BTS Skytrain is best for getting around', 'Visit temples before 9am', 'Carry cash as many places don\'t accept cards', 'Bargain at markets respectfully'], safetyRating: 7, languageBarrier: 'medium', currency: 'THB', timezoneName: 'Asia/Bangkok', utcOffset: 7, isPopular: 1, isTrending: 1, isHiddenGem: 0, rank: 2 },
    { slug: 'bali-indonesia', name: 'Bali', country: 'Indonesia', countryCode: 'ID', continent: 'asia', lat: '-8.3405', lng: '115.0920', airportCodes: ['DPS'], heroImageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80', tagline: 'Island of Gods — Serenity, Temples & Terraces', description: 'Bali enchants with emerald rice terraces, ancient temples perched on clifftops, surf beaches, and a vibrant wellness scene. The spiritual heart of Indonesia.', moodsJson: ['beaches', 'spiritual', 'wellness', 'adventure', 'romance'], scoreJson: { overall: 93, affordability: 80, safety: 80, weatherScore: 75, touristInfrastructure: 88, uniqueness: 95, visaEase: 80, travelTime: 90, communityRating: 95, badge: 'trending' }, budgetJson: { budget: { amount: 2500, currency: 'INR', formatted: '₹2,500' }, comfort: { amount: 5000, currency: 'INR', formatted: '₹5,000' }, luxury: { amount: 18000, currency: 'INR', formatted: '₹18,000' }, flightFrom: { amount: 11000, currency: 'INR', formatted: '₹11,000' }, averageHotelPerNight: { amount: 2500, currency: 'INR', formatted: '₹2,500' }, averageMealCost: { amount: 350, currency: 'INR', formatted: '₹350' } }, visaJson: { type: 'visa_on_arrival', durationDays: 30, feeUsd: 35, processingDays: 0 }, highlightsJson: [], bestTimeJson: [{ months: [5, 6, 7, 8, 9], reason: 'Dry season — best for beaches and temple visits', weather: 'Sunny, 27-32°C', crowdLevel: 'high', priceLevel: 'peak' }], popularActivities: ['Tanah Lot Temple', 'Tegalalang Rice Terraces', 'Ubud Monkey Forest', 'Mount Batur Sunrise Trek', 'Uluwatu Temple', 'Seminyak Beach', 'Nusa Penida Day Trip', 'Balinese Cooking Class'], cuisineHighlights: ['Nasi Goreng', 'Babi Guling', 'Satay', 'Gado-Gado', 'Black Rice Pudding'], localTips: ['Rent a scooter for flexibility', 'Learn basic Indonesian phrases', 'Respect temple dress codes (sarong required)', 'Bargain at art markets'], safetyRating: 8, languageBarrier: 'low', currency: 'IDR', timezoneName: 'Asia/Makassar', utcOffset: 8, isPopular: 1, isTrending: 1, isHiddenGem: 0, rank: 3 },
    { slug: 'singapore', name: 'Singapore', country: 'Singapore', countryCode: 'SG', continent: 'asia', lat: '1.3521', lng: '103.8198', airportCodes: ['SIN'], heroImageUrl: 'https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&q=80', tagline: 'The Lion City — Where East Meets West', description: 'Singapore is a gleaming city-state where futuristic architecture meets lush gardens, and hawker food stands next to Michelin-starred restaurants.', moodsJson: ['food', 'shopping', 'family', 'culture'], scoreJson: { overall: 90, affordability: 35, safety: 99, weatherScore: 70, touristInfrastructure: 100, uniqueness: 80, visaEase: 95, travelTime: 87, communityRating: 88, badge: 'family_friendly' }, budgetJson: { budget: { amount: 6000, currency: 'INR', formatted: '₹6,000' }, comfort: { amount: 10000, currency: 'INR', formatted: '₹10,000' }, luxury: { amount: 25000, currency: 'INR', formatted: '₹25,000' }, flightFrom: { amount: 8000, currency: 'INR', formatted: '₹8,000' }, averageHotelPerNight: { amount: 7000, currency: 'INR', formatted: '₹7,000' }, averageMealCost: { amount: 800, currency: 'INR', formatted: '₹800' } }, visaJson: { type: 'visa_free', durationDays: 30, feeUsd: 0 }, highlightsJson: [], bestTimeJson: [{ months: [2, 3, 4, 7, 8], reason: 'Slightly drier months with pleasant weather', weather: 'Warm and humid, 25-32°C', crowdLevel: 'medium', priceLevel: 'moderate' }], popularActivities: ['Gardens by the Bay', 'Marina Bay Sands', 'Sentosa Island', 'Hawker Centers', 'Universal Studios', 'Little India', 'Chinatown', 'Orchard Road Shopping'], cuisineHighlights: ['Hainanese Chicken Rice', 'Chilli Crab', 'Laksa', 'Char Kway Teow', 'Kaya Toast'], localTips: ['Get EZ-Link card for public transport', 'Eat at hawker centers to save money', 'Avoid chewing gum — it\'s banned', 'MRT is the most efficient way to get around'], safetyRating: 10, languageBarrier: 'none', currency: 'SGD', timezoneName: 'Asia/Singapore', utcOffset: 8, isPopular: 1, isTrending: 0, isHiddenGem: 0, rank: 4 },
    { slug: 'maldives', name: 'Maldives', country: 'Maldives', countryCode: 'MV', continent: 'asia', lat: '3.2028', lng: '73.2207', airportCodes: ['MLE'], heroImageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80', tagline: 'Paradise on Earth — Crystal Waters & Overwater Bliss', description: 'The Maldives offers an unmatched tropical paradise experience — crystal-clear lagoons, vibrant coral reefs, and ultra-luxurious overwater bungalows.', moodsJson: ['beaches', 'romance', 'wellness', 'adventure'], scoreJson: { overall: 95, affordability: 15, safety: 90, weatherScore: 90, touristInfrastructure: 85, uniqueness: 99, visaEase: 99, travelTime: 88, communityRating: 97, badge: 'luxury' }, budgetJson: { budget: { amount: 15000, currency: 'INR', formatted: '₹15,000' }, comfort: { amount: 30000, currency: 'INR', formatted: '₹30,000' }, luxury: { amount: 80000, currency: 'INR', formatted: '₹80,000' }, flightFrom: { amount: 20000, currency: 'INR', formatted: '₹20,000' }, averageHotelPerNight: { amount: 25000, currency: 'INR', formatted: '₹25,000' }, averageMealCost: { amount: 3000, currency: 'INR', formatted: '₹3,000' } }, visaJson: { type: 'visa_free', durationDays: 30, feeUsd: 0, notes: 'Free 30-day visitor visa on arrival' }, highlightsJson: [], bestTimeJson: [{ months: [11, 12, 1, 2, 3, 4], reason: 'Dry season — perfect weather for snorkeling', weather: 'Sunny, 26-30°C', crowdLevel: 'high', priceLevel: 'peak' }], popularActivities: ['Overwater Bungalow', 'Snorkeling & Diving', 'Sunset Cruise', 'Whale Shark Spotting', 'Island Hopping', 'Bioluminescent Beach', 'Dolphin Watching', 'Manta Ray Diving'], cuisineHighlights: ['Garudhiya', 'Mas Huni', 'Hedhikaa', 'Kulhi Boakibaa'], localTips: ['Book resorts well in advance', 'Local islands are budget-friendly', 'Seaplane transfers are expensive — check ferry options', 'Alcohol only at resort islands'], safetyRating: 9, languageBarrier: 'low', currency: 'MVR', timezoneName: 'Indian/Maldives', utcOffset: 5, isPopular: 1, isTrending: 0, isHiddenGem: 0, rank: 5 },
    // India domestic
    { slug: 'goa-india', name: 'Goa', country: 'India', countryCode: 'IN', continent: 'asia', lat: '15.2993', lng: '74.1240', airportCodes: ['GOI'], heroImageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80', tagline: 'Sun, Sea & Spice — India\'s Beach Paradise', description: 'Goa blends Portuguese heritage with Indian warmth. Stunning beaches, seafood shacks, vibrant nightlife, and colonial churches make it India\'s most beloved coastal destination.', moodsJson: ['beaches', 'nightlife', 'food', 'culture', 'budget'], scoreJson: { overall: 88, affordability: 82, safety: 75, weatherScore: 78, touristInfrastructure: 88, uniqueness: 75, visaEase: 99, travelTime: 90, communityRating: 90, badge: 'best_value' }, budgetJson: { budget: { amount: 1500, currency: 'INR', formatted: '₹1,500' }, comfort: { amount: 3500, currency: 'INR', formatted: '₹3,500' }, luxury: { amount: 10000, currency: 'INR', formatted: '₹10,000' }, flightFrom: { amount: 4000, currency: 'INR', formatted: '₹4,000' }, averageHotelPerNight: { amount: 2000, currency: 'INR', formatted: '₹2,000' }, averageMealCost: { amount: 400, currency: 'INR', formatted: '₹400' } }, visaJson: { type: 'visa_free', durationDays: 365 }, highlightsJson: [], bestTimeJson: [{ months: [11, 12, 1, 2, 3], reason: 'Peak season with perfect beach weather', weather: 'Sunny, 25-32°C', crowdLevel: 'high', priceLevel: 'peak' }], popularActivities: ['Calangute Beach', 'Baga Beach', 'Old Goa Churches', 'Dudhsagar Falls', 'Anjuna Flea Market', 'Spice Plantation Tour', 'Cruise on Mandovi River', 'Water Sports'], cuisineHighlights: ['Fish Curry Rice', 'Prawn Balchao', 'Cafreal', 'Bebinca', 'Sorpotel'], localTips: ['Rent a scooty for beach-hopping', 'South Goa is calmer and cleaner', 'Avoid monsoon season (Jun-Sep)', 'Book beach shacks in advance during peak season'], safetyRating: 7, languageBarrier: 'none', currency: 'INR', timezoneName: 'Asia/Kolkata', utcOffset: 5.5, isPopular: 1, isTrending: 1, isHiddenGem: 0, rank: 6 },
    { slug: 'kerala-india', name: 'Kerala', country: 'India', countryCode: 'IN', continent: 'asia', lat: '10.8505', lng: '76.2711', airportCodes: ['COK', 'TRV', 'CCJ'], heroImageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80', tagline: 'God\'s Own Country — Backwaters & Serenity', description: 'Kerala offers a magical escape into tranquil backwaters, misty hill stations, ancient Ayurvedic traditions, and pristine beaches. The most unique landscape in India.', moodsJson: ['nature', 'wellness', 'family', 'culture', 'budget'], scoreJson: { overall: 91, affordability: 80, safety: 88, weatherScore: 72, touristInfrastructure: 85, uniqueness: 92, visaEase: 99, travelTime: 85, communityRating: 93, badge: 'hidden_gem' }, budgetJson: { budget: { amount: 1800, currency: 'INR', formatted: '₹1,800' }, comfort: { amount: 4000, currency: 'INR', formatted: '₹4,000' }, luxury: { amount: 12000, currency: 'INR', formatted: '₹12,000' }, flightFrom: { amount: 5000, currency: 'INR', formatted: '₹5,000' }, averageHotelPerNight: { amount: 2500, currency: 'INR', formatted: '₹2,500' }, averageMealCost: { amount: 350, currency: 'INR', formatted: '₹350' } }, visaJson: { type: 'visa_free', durationDays: 365 }, highlightsJson: [], bestTimeJson: [{ months: [10, 11, 12, 1, 2, 3], reason: 'Post-monsoon — everything is lush green', weather: 'Pleasant, 22-30°C', crowdLevel: 'medium', priceLevel: 'moderate' }], popularActivities: ['Alleppey Houseboat', 'Munnar Tea Gardens', 'Periyar Wildlife Sanctuary', 'Kovalam Beach', 'Kathakali Performance', 'Ayurvedic Massage', 'Wayanad Trekking', 'Thekkady Spice Tour'], cuisineHighlights: ['Kerala Fish Curry', 'Appam with Stew', 'Puttu Kadala', 'Prawn Moilee', 'Payasam'], localTips: ['Monsoon is actually beautiful in Kerala', 'Book houseboats 3 months in advance', 'Try fresh coconut water everywhere', 'Hire a local guide for wildlife sanctuaries'], safetyRating: 9, languageBarrier: 'low', currency: 'INR', timezoneName: 'Asia/Kolkata', utcOffset: 5.5, isPopular: 1, isTrending: 0, isHiddenGem: 0, rank: 7 },
    { slug: 'rajasthan-india', name: 'Rajasthan', country: 'India', countryCode: 'IN', continent: 'asia', lat: '27.0238', lng: '74.2179', airportCodes: ['JAI', 'UDR', 'JDH', 'BKB'], heroImageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed31acb?w=800&q=80', tagline: 'The Land of Kings — Forts, Palaces & Saffron Sands', description: 'Rajasthan is India\'s most regal state — majestic forts, opulent palaces, vibrant bazaars, camel safaris through golden dunes, and a culture that has stood for centuries.', moodsJson: ['culture', 'adventure', 'shopping', 'family'], scoreJson: { overall: 89, affordability: 78, safety: 80, weatherScore: 65, touristInfrastructure: 87, uniqueness: 94, visaEase: 99, travelTime: 88, communityRating: 91, badge: 'adventure' }, budgetJson: { budget: { amount: 2000, currency: 'INR', formatted: '₹2,000' }, comfort: { amount: 5000, currency: 'INR', formatted: '₹5,000' }, luxury: { amount: 20000, currency: 'INR', formatted: '₹20,000' }, flightFrom: { amount: 4500, currency: 'INR', formatted: '₹4,500' }, averageHotelPerNight: { amount: 3000, currency: 'INR', formatted: '₹3,000' }, averageMealCost: { amount: 400, currency: 'INR', formatted: '₹400' } }, visaJson: { type: 'visa_free', durationDays: 365 }, highlightsJson: [], bestTimeJson: [{ months: [10, 11, 12, 1, 2], reason: 'Winter is cool and perfect for exploration', weather: 'Cool, 15-25°C', crowdLevel: 'high', priceLevel: 'peak' }], popularActivities: ['Jaipur City Palace', 'Amber Fort', 'Jaisalmer Desert Safari', 'Udaipur Lake Palace', 'Pushkar Camel Fair', 'Mehrangarh Fort Jodhpur', 'Ranthambore Tiger Safari', 'Hawa Mahal'], cuisineHighlights: ['Dal Baati Churma', 'Laal Maas', 'Ghevar', 'Ker Sangri', 'Rajasthani Thali'], localTips: ['Hire a guide at major forts for context', 'Bargain firmly but respectfully at bazaars', 'Avoid peak summer (May-Jun)', 'Heritage hotels are worth the splurge'], safetyRating: 7, languageBarrier: 'medium', currency: 'INR', timezoneName: 'Asia/Kolkata', utcOffset: 5.5, isPopular: 1, isTrending: 0, isHiddenGem: 0, rank: 8 },
  ];

  await db.insert(destinations).values(destinationData).onConflictDoNothing();
  logger.info(`Seeded ${destinationData.length} destinations`);

  // ─── Flash Deals ──────────────────────────────────────────────────────────
  const flashDealData: (typeof flashDeals.$inferInsert)[] = [
    { title: 'Mumbai → Dubai Flash Sale', subtitle: 'Limited seats — book now!', origin: 'Mumbai (BOM)', destination: 'Dubai (DXB)', imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80', salePriceAmount: 14999, salePriceCurrency: 'INR', originalPriceAmount: 28000, platform: 'makemytrip', deeplink: 'https://www.makemytrip.com', expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000), seatsLeft: 7, isLive: true, dealType: 'flash', travelWindowFrom: '2026-05-01', travelWindowTo: '2026-05-31' },
    { title: 'Delhi → Bangkok Super Deal', subtitle: 'Price drop — act fast!', origin: 'Delhi (DEL)', destination: 'Bangkok (BKK)', imageUrl: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80', salePriceAmount: 7999, salePriceCurrency: 'INR', originalPriceAmount: 14500, platform: 'goibibo', deeplink: 'https://www.goibibo.com', expiresAt: new Date(Date.now() + 48 * 60 * 60 * 1000), seatsLeft: 12, isLive: true, dealType: 'sale', travelWindowFrom: '2026-06-01', travelWindowTo: '2026-06-30' },
    { title: 'Bangalore → Bali Getaway', subtitle: 'Weekend escape starting ₹11k!', origin: 'Bangalore (BLR)', destination: 'Bali (DPS)', imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80', salePriceAmount: 10999, salePriceCurrency: 'INR', originalPriceAmount: 22000, platform: 'cleartrip', deeplink: 'https://www.cleartrip.com', expiresAt: new Date(Date.now() + 72 * 60 * 60 * 1000), seatsLeft: 5, isLive: true, dealType: 'flash', travelWindowFrom: '2026-07-01', travelWindowTo: '2026-07-31' },
  ];

  await db.insert(flashDeals).values(flashDealData).onConflictDoNothing();
  logger.info(`Seeded ${flashDealData.length} flash deals`);

  logger.info('✅ Database seeded successfully!');
  process.exit(0);
}

seed().catch((err) => {
  logger.error({ err }, 'Seed failed');
  process.exit(1);
});
